import type { InventoryItem, Category, Supplier, StockMovement } from "@/types/inventory"

export const mockCategories: Category[] = [
  { id: "1", name: "Ciment et Béton", description: "Ciments, bétons prêts à l'emploi" },
  { id: "2", name: "Briques et Blocs", description: "Briques, parpaings, blocs béton" },
  { id: "3", name: "Sable et Granulats", description: "Sables, graviers, granulats" },
  { id: "4", name: "Bois de Construction", description: "Planches, poutres, chevrons" },
  { id: "5", name: "Isolation", description: "Matériaux isolants thermiques et phoniques" },
]

export const mockSuppliers: Supplier[] = [
  {
    id: "1",
    name: "Lafarge France",
    contact: "Jean Dupont",
    email: "contact@lafarge.fr",
    phone: "01 23 45 67 89",
    address: "123 Rue de l'Industrie, 75001 Paris",
  },
  {
    id: "2",
    name: "Point P",
    contact: "Marie Martin",
    email: "commandes@pointp.fr",
    phone: "01 98 76 54 32",
    address: "456 Avenue du Commerce, 69000 Lyon",
  },
  {
    id: "3",
    name: "Gedimat",
    contact: "Pierre Durand",
    email: "pro@gedimat.fr",
    phone: "02 34 56 78 90",
    address: "789 Boulevard des Matériaux, 13000 Marseille",
  },
]

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "1",
    name: "Ciment Portland CEM I 52.5",
    description: "Ciment haute performance pour béton armé",
    category: "Ciment et Béton",
    supplier: "Lafarge France",
    unit: "sacs",
    currentStock: 150,
    reorderLevel: 50,
    unitPrice: 8.5,
    totalValue: 1275,
    lastUpdated: new Date("2024-01-15"),
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "2",
    name: "Briques rouges pleines",
    description: "Briques traditionnelles 22x10.5x6.5cm",
    category: "Briques et Blocs",
    supplier: "Point P",
    unit: "pieces",
    currentStock: 15,
    reorderLevel: 100,
    unitPrice: 0.45,
    totalValue: 6.75,
    lastUpdated: new Date("2024-01-10"),
    createdAt: new Date("2023-05-15"),
  },
  {
    id: "3",
    name: "Sable fin 0/2",
    description: "Sable fin pour mortier et enduits",
    category: "Sable et Granulats",
    supplier: "Gedimat",
    unit: "tonnes",
    currentStock: 2.5,
    reorderLevel: 5,
    unitPrice: 35.0,
    totalValue: 87.5,
    lastUpdated: new Date("2024-01-12"),
    createdAt: new Date("2023-07-01"),
  },
  {
    id: "4",
    name: "Parpaings creux 20x20x50",
    description: "Blocs béton pour murs porteurs",
    category: "Briques et Blocs",
    supplier: "Lafarge France",
    unit: "pieces",
    currentStock: 500,
    reorderLevel: 200,
    unitPrice: 2.8,
    totalValue: 1400,
    lastUpdated: new Date("2024-01-14"),
    createdAt: new Date("2023-08-01"),
  },
  {
    id: "5",
    name: "Laine de verre 100mm",
    description: "Isolation thermique et phonique",
    category: "Isolation",
    supplier: "Point P",
    unit: "m2",
    currentStock: 250,
    reorderLevel: 100,
    unitPrice: 4.2,
    totalValue: 1050,
    lastUpdated: new Date("2024-01-13"),
    createdAt: new Date("2023-09-01"),
  },
]

export const mockStockMovements: StockMovement[] = [
  {
    id: "1",
    itemId: "1",
    type: "in",
    quantity: 50,
    reason: "Livraison fournisseur",
    userId: "2",
    userName: "Responsable Inventaire",
    date: new Date("2024-01-15"),
  },
  {
    id: "2",
    itemId: "2",
    type: "out",
    quantity: 85,
    reason: "Commande client CMD-2024-001",
    userId: "3",
    userName: "Responsable Commercial",
    date: new Date("2024-01-10"),
  },
  {
    id: "3",
    itemId: "3",
    type: "adjustment",
    quantity: -0.5,
    reason: "Correction inventaire",
    userId: "2",
    userName: "Responsable Inventaire",
    date: new Date("2024-01-12"),
  },
]
