import type { Quote, Invoice, Payment } from "@/types/invoicing"

export const mockQuotes: Quote[] = [
  {
    id: "1",
    quoteNumber: "DEV-2024-001",
    customerId: "1",
    customerName: "Jean Dupont",
    customerCompany: "Entreprise Dupont SARL",
    items: [
      {
        id: "1",
        itemId: "1",
        itemName: "Ciment Portland CEM I 52.5",
        quantity: 30,
        unitPrice: 8.5,
        totalPrice: 255,
        unit: "sacs",
      },
      {
        id: "2",
        itemId: "4",
        itemName: "Parpaings creux 20x20x50",
        quantity: 200,
        unitPrice: 2.8,
        totalPrice: 560,
        unit: "pieces",
      },
    ],
    subtotal: 815,
    taxRate: 20,
    taxAmount: 163,
    total: 978,
    status: "sent",
    validUntil: new Date("2024-02-15"),
    quoteDate: new Date("2024-01-15"),
    notes: "Devis valable 30 jours",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "2",
    quoteNumber: "DEV-2024-002",
    customerId: "2",
    customerName: "Marie Martin",
    customerCompany: "Martin BTP",
    items: [
      {
        id: "3",
        itemId: "5",
        itemName: "Laine de verre 100mm",
        quantity: 100,
        unitPrice: 4.2,
        totalPrice: 420,
        unit: "m2",
      },
    ],
    subtotal: 420,
    taxRate: 20,
    taxAmount: 84,
    total: 504,
    status: "accepted",
    validUntil: new Date("2024-02-20"),
    quoteDate: new Date("2024-01-20"),
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "1",
    invoiceNumber: "FAC-2024-001",
    orderId: "1",
    customerId: "1",
    customerName: "Jean Dupont",
    customerCompany: "Entreprise Dupont SARL",
    customerEmail: "jean.dupont@entreprise-dupont.fr",
    customerAddress: "123 Rue de la Construction, 75001 Paris",
    customerTaxId: "FR12345678901",
    items: [
      {
        id: "1",
        itemId: "1",
        itemName: "Ciment Portland CEM I 52.5",
        quantity: 20,
        unitPrice: 8.5,
        totalPrice: 170,
        unit: "sacs",
      },
      {
        id: "2",
        itemId: "4",
        itemName: "Parpaings creux 20x20x50",
        quantity: 100,
        unitPrice: 2.8,
        totalPrice: 280,
        unit: "pieces",
      },
    ],
    subtotal: 450,
    taxRate: 20,
    taxAmount: 90,
    total: 540,
    paidAmount: 540,
    remainingAmount: 0,
    status: "paid",
    invoiceDate: new Date("2024-01-15"),
    dueDate: new Date("2024-02-14"),
    paidDate: new Date("2024-01-20"),
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "2",
    invoiceNumber: "FAC-2024-002",
    orderId: "2",
    customerId: "2",
    customerName: "Marie Martin",
    customerCompany: "Martin BTP",
    customerEmail: "marie@martin-btp.fr",
    customerAddress: "456 Avenue des Bâtisseurs, 69000 Lyon",
    customerTaxId: "FR98765432109",
    items: [
      {
        id: "3",
        itemId: "2",
        itemName: "Briques rouges pleines",
        quantity: 500,
        unitPrice: 0.45,
        totalPrice: 225,
        unit: "pieces",
      },
      {
        id: "4",
        itemId: "3",
        itemName: "Sable fin 0/2",
        quantity: 3,
        unitPrice: 35.0,
        totalPrice: 105,
        unit: "tonnes",
      },
    ],
    subtotal: 330,
    taxRate: 20,
    taxAmount: 66,
    total: 396,
    paidAmount: 200,
    remainingAmount: 196,
    status: "partial",
    invoiceDate: new Date("2024-01-12"),
    dueDate: new Date("2024-02-11"),
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "3",
    invoiceNumber: "FAC-2024-003",
    customerId: "3",
    customerName: "Pierre Durand",
    customerEmail: "pierre.durand@gmail.com",
    customerAddress: "789 Boulevard du Chantier, 13000 Marseille",
    items: [
      {
        id: "5",
        itemId: "5",
        itemName: "Laine de verre 100mm",
        quantity: 50,
        unitPrice: 4.2,
        totalPrice: 210,
        unit: "m2",
      },
    ],
    subtotal: 210,
    taxRate: 20,
    taxAmount: 42,
    total: 252,
    paidAmount: 0,
    remainingAmount: 252,
    status: "overdue",
    invoiceDate: new Date("2023-12-15"),
    dueDate: new Date("2024-01-14"),
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
]

export const mockPayments: Payment[] = [
  {
    id: "1",
    invoiceId: "1",
    amount: 540,
    paymentMethod: "transfer",
    paymentDate: new Date("2024-01-20"),
    reference: "VIR-20240120-001",
    notes: "Paiement intégral par virement",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "2",
    invoiceId: "2",
    amount: 200,
    paymentMethod: "check",
    paymentDate: new Date("2024-01-15"),
    reference: "CHQ-123456",
    notes: "Acompte de 50%",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
]
