import type { Customer, Order, Reservation } from "@/types/orders"

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "Jean Dupont",
    company: "Entreprise Dupont SARL",
    email: "jean.dupont@entreprise-dupont.fr",
    phone: "01 23 45 67 89",
    address: "123 Rue de la Construction, 75001 Paris",
    taxId: "FR12345678901",
    createdAt: new Date("2023-01-15"),
  },
  {
    id: "2",
    name: "Marie Martin",
    company: "Martin BTP",
    email: "marie@martin-btp.fr",
    phone: "02 34 56 78 90",
    address: "456 Avenue des Bâtisseurs, 69000 Lyon",
    taxId: "FR98765432109",
    createdAt: new Date("2023-02-20"),
  },
  {
    id: "3",
    name: "Pierre Durand",
    email: "pierre.durand@gmail.com",
    phone: "03 45 67 89 01",
    address: "789 Boulevard du Chantier, 13000 Marseille",
    createdAt: new Date("2023-03-10"),
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "CMD-2024-001",
    customerId: "1",
    customerName: "Jean Dupont",
    customerCompany: "Entreprise Dupont SARL",
    items: [
      {
        id: "1",
        itemId: "1",
        itemName: "Ciment Portland CEM I 52.5",
        quantity: 20,
        unitPrice: 8.5,
        totalPrice: 170,
        unit: "sacs",
      },
      {
        id: "2",
        itemId: "4",
        itemName: "Parpaings creux 20x20x50",
        quantity: 100,
        unitPrice: 2.8,
        totalPrice: 280,
        unit: "pieces",
      },
    ],
    subtotal: 450,
    taxRate: 20,
    taxAmount: 90,
    total: 540,
    status: "delivered",
    orderDate: new Date("2024-01-10"),
    deliveryDate: new Date("2024-01-15"),
    deliveryAddress: "123 Rue de la Construction, 75001 Paris",
    notes: "Livraison le matin de préférence",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "2",
    orderNumber: "CMD-2024-002",
    customerId: "2",
    customerName: "Marie Martin",
    customerCompany: "Martin BTP",
    items: [
      {
        id: "3",
        itemId: "2",
        itemName: "Briques rouges pleines",
        quantity: 500,
        unitPrice: 0.45,
        totalPrice: 225,
        unit: "pieces",
      },
      {
        id: "4",
        itemId: "3",
        itemName: "Sable fin 0/2",
        quantity: 3,
        unitPrice: 35.0,
        totalPrice: 105,
        unit: "tonnes",
      },
    ],
    subtotal: 330,
    taxRate: 20,
    taxAmount: 66,
    total: 396,
    status: "reserved",
    orderDate: new Date("2024-01-12"),
    deliveryAddress: "456 Avenue des Bâtisseurs, 69000 Lyon",
    notes: "Stock réservé jusqu'au 25/01",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
  {
    id: "3",
    orderNumber: "CMD-2024-003",
    customerId: "3",
    customerName: "Pierre Durand",
    items: [
      {
        id: "5",
        itemId: "5",
        itemName: "Laine de verre 100mm",
        quantity: 50,
        unitPrice: 4.2,
        totalPrice: 210,
        unit: "m2",
      },
    ],
    subtotal: 210,
    taxRate: 20,
    taxAmount: 42,
    total: 252,
    status: "pending",
    orderDate: new Date("2024-01-14"),
    deliveryAddress: "789 Boulevard du Chantier, 13000 Marseille",
    createdBy: "3",
    createdByName: "Responsable Commercial",
  },
]

export const mockReservations: Reservation[] = [
  {
    id: "1",
    orderId: "2",
    itemId: "2",
    itemName: "Briques rouges pleines",
    quantity: 500,
    reservedUntil: new Date("2024-01-25"),
    status: "active",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "2",
    orderId: "2",
    itemId: "3",
    itemName: "Sable fin 0/2",
    quantity: 3,
    reservedUntil: new Date("2024-01-25"),
    status: "active",
    createdAt: new Date("2024-01-12"),
  },
]
