import type { SystemSettings, AuditLog, SystemStats } from "@/types/admin"
import type { User } from "@/types/auth"

export const mockSystemSettings: SystemSettings = {
  id: "1",
  companyName: "BuildStock SARL",
  companyAddress: "123 Rue de l'Industrie, 75001 Paris, France",
  companyPhone: "+33 1 23 45 67 89",
  companyEmail: "contact@buildstock.fr",
  taxRate: 20,
  currency: "EUR",
  invoicePrefix: "FAC",
  orderPrefix: "CMD",
  quotePrefix: "DEV",
  lowStockThreshold: 10,
  autoReorderEnabled: false,
  emailNotifications: true,
  smsNotifications: false,
  backupFrequency: "daily",
  lastBackup: new Date("2024-01-15T02:00:00Z"),
  updatedAt: new Date("2024-01-10"),
  updatedBy: "Admin Utilisateur",
}

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@buildstock.fr",
    name: "Admin Utilisateur",
    role: "admin",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "inventaire@buildstock.fr",
    name: "Responsable Inventaire",
    role: "inventory_manager",
    createdAt: new Date("2023-02-15"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    email: "commercial@buildstock.fr",
    name: "Responsable Commercial",
    role: "commercial_manager",
    createdAt: new Date("2023-03-01"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "4",
    email: "sophie.martin@buildstock.fr",
    name: "Sophie Martin",
    role: "inventory_manager",
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-01-08"),
  },
  {
    id: "5",
    email: "lucas.bernard@buildstock.fr",
    name: "Lucas Bernard",
    role: "commercial_manager",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-01-14"),
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    userId: "2",
    userName: "Responsable Inventaire",
    userRole: "inventory_manager",
    action: "CREATE",
    entity: "inventory_item",
    entityId: "6",
    details: "Ajout d'un nouvel article: Ciment blanc CEM II",
    ipAddress: "192.168.1.100",
    timestamp: new Date("2024-01-15T10:30:00Z"),
  },
  {
    id: "2",
    userId: "3",
    userName: "Responsable Commercial",
    userRole: "commercial_manager",
    action: "UPDATE",
    entity: "order",
    entityId: "2",
    details: "Changement de statut: En attente → Réservé",
    ipAddress: "192.168.1.101",
    timestamp: new Date("2024-01-15T09:15:00Z"),
  },
  {
    id: "3",
    userId: "1",
    userName: "Admin Utilisateur",
    userRole: "admin",
    action: "CREATE",
    entity: "user",
    entityId: "5",
    details: "Création d'un nouvel utilisateur: Lucas Bernard",
    ipAddress: "192.168.1.102",
    timestamp: new Date("2024-01-14T16:45:00Z"),
  },
  {
    id: "4",
    userId: "3",
    userName: "Responsable Commercial",
    userRole: "commercial_manager",
    action: "CREATE",
    entity: "invoice",
    entityId: "4",
    details: "Création de la facture FAC-2024-004",
    ipAddress: "192.168.1.101",
    timestamp: new Date("2024-01-14T14:20:00Z"),
  },
  {
    id: "5",
    userId: "2",
    userName: "Responsable Inventaire",
    userRole: "inventory_manager",
    action: "UPDATE",
    entity: "inventory_item",
    entityId: "2",
    details: "Mise à jour du stock: Briques rouges pleines (15 → 500)",
    ipAddress: "192.168.1.100",
    timestamp: new Date("2024-01-14T11:30:00Z"),
  },
  {
    id: "6",
    userId: "1",
    userName: "Admin Utilisateur",
    userRole: "admin",
    action: "UPDATE",
    entity: "system_settings",
    entityId: "1",
    details: "Modification des paramètres système: Seuil de stock faible (5 → 10)",
    ipAddress: "192.168.1.102",
    timestamp: new Date("2024-01-13T08:00:00Z"),
  },
]

export const mockSystemStats: SystemStats = {
  totalUsers: 5,
  activeUsers: 4,
  totalInventoryItems: 125,
  lowStockItems: 8,
  totalOrders: 47,
  pendingOrders: 12,
  totalInvoices: 156,
  overdueInvoices: 3,
  totalRevenue: 125430.5,
  monthlyRevenue: 18750.25,
}
